Name:           ros-hydro-object-recognition-ros-visualization
Version:        0.3.5
Release:        0%{?dist}
Summary:        ROS object_recognition_ros_visualization package

Group:          Development/Libraries
License:        BSD
URL:            wg-perception.github.io/object_recognition_ros
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       ros-hydro-object-recognition-msgs
Requires:       ros-hydro-object-recognition-ros
Requires:       ros-hydro-pluginlib
Requires:       ros-hydro-rviz
BuildRequires:  boost-devel
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-object-recognition-msgs
BuildRequires:  ros-hydro-object-recognition-ros
BuildRequires:  ros-hydro-pluginlib
BuildRequires:  ros-hydro-rviz

%description
object_recognition_ros_visualization contains rviz plugins to visualize ork
detection results

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Sat Sep 20 2014 Vincent Rabaud <vincent.rabaud@gmail.com> - 0.3.5-0
- Autogenerated by Bloom

* Thu Sep 18 2014 Vincent Rabaud <vincent.rabaud@gmail.com> - 0.3.3-0
- Autogenerated by Bloom

* Sat Sep 20 2014 Vincent Rabaud <vincent.rabaud@gmail.com> - 0.3.4-0
- Autogenerated by Bloom

